<?php

namespace AppBundle\Repository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllSortedByName() {
        $qb =  $this->createQueryBuilder('a')->orderBy('a.name', 'ASC');


        $query = $qb->getQuery();
        // dump($query->getDQL()); die;
        return $query->getResult();
    }
}
